env:
  browser: true
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars": error
  "@typescript-eslint/no-var-requires": 0
  eol-last:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  comma-spacing:
    - error
    - before: false
      after: true
